server:
  port: 8003

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/micro
    username: root
    password: root  
   
  application:
    name: CustomerInfo  
    
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
        
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: 
         defaultZone: http://localhost:8004/eureka
        
    
           
      
              
      

               
    
           
         
           
   

      
             
                 

      



        
    
    